/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop2.school;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import static javax.swing.JOptionPane.showMessageDialog;
import oop2.lecture.Lecture;
import oop2.professer.Professer;
import oop2.student.Student;

/**
 *
 * @author 김부성
 */
public class School_insert_user extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public School_insert_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        insert_Info = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        insert_Ok = new javax.swing.JButton();
        insert_Exit = new javax.swing.JButton();
        lec_butt = new javax.swing.JRadioButton();
        stu_butt = new javax.swing.JRadioButton();
        pro_butt = new javax.swing.JRadioButton();
        sch_butt = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        pNum = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        depart_list = new javax.swing.JComboBox<>();

        jTabbedPane2.addTab("tab1", jTabbedPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        insert_Info.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("사용자 등록");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel1.setText("사용자 등록");

        insert_Ok.setText("등록");
        insert_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_OkActionPerformed(evt);
            }
        });

        insert_Exit.setText("취소");

        buttonGroup1.add(lec_butt);
        lec_butt.setText("수업");

        buttonGroup1.add(stu_butt);
        stu_butt.setText("학생");

        buttonGroup1.add(pro_butt);
        pro_butt.setText("교수");

        buttonGroup1.add(sch_butt);
        sch_butt.setText("학사");

        jLabel4.setText("주민번호 : ");

        jLabel2.setText("이름  : ");

        depart_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "전산학과", "전자공학과", "화학공학과", "기계공학과", "항공우주공학과" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sch_butt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depart_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lec_butt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stu_butt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pro_butt))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(insert_Ok)
                        .addGap(47, 47, 47)
                        .addComponent(insert_Exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lec_butt)
                    .addComponent(stu_butt)
                    .addComponent(pro_butt)
                    .addComponent(sch_butt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depart_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_Ok)
                    .addComponent(insert_Exit))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_OkActionPerformed
        // TODO add your handling code here:
        String str;
        if(name.getText().isEmpty()){
            showMessageDialog(null,"이름을 입력해주세요!!");
        }else if(pNum.getText().isEmpty() || pNum.getText().length() != 13){
            showMessageDialog(null,"주민번호를 입력해주세요!!");
        }else{
            if(sch_butt.isSelected()){ //학사관리자 파일에 입력
                try{
                    FileOutputStream file = new FileOutputStream("school.txt",true);//파일 열기
                    OutputStreamWriter output = new OutputStreamWriter(file,"euc-kr");
                    BufferedWriter writer = new BufferedWriter(output);
                    School sch = new School(pNum.getText(), name.getText()); //학사관리자 생성자로 객체 생성
                    str = String.format("%s/%s/%s/%s%n",sch.getId(),sch.getName(),sch.getPassWord(),sch.getPeopleNum());
                    //문자열로 저장, 나중에 읽을 때 "/"단위로 끊어서 읽기 위함
                    writer.write(str); //파일에 객체 정보를 저장
                    writer.close(); //사용 후 파일 닫기
                    showMessageDialog(null,sch.getId() +" " + sch.getName() + "직원이 등록 되었습니다.");//완료 메시지
                }catch(IOException e){
                    e.printStackTrace();
                }
            }else if(lec_butt.isSelected()){//수업 관리자 파일에 입력
                try{
                    FileOutputStream file = new FileOutputStream("lecture.txt",true);//파일 열기
                    OutputStreamWriter output = new OutputStreamWriter(file,"euc-kr");
                    BufferedWriter writer = new BufferedWriter(output);
                    Lecture lec = new Lecture(pNum.getText(), name.getText());
                    str = String.format("%s/%s/%s/%s%n",lec.getId(),lec.getName(),lec.getPassWord(),lec.getPeopleNum());
                    writer.write(str); //파일에 객체 정보를 저장
                    writer.close();
                    showMessageDialog(null,lec.getId() +" " + lec.getName() + "직원이 등록 되었습니다.");
                }catch(IOException e){
                    e.printStackTrace();
                }
            }else if(stu_butt.isSelected()){ //학생 파일에 입력
                 try{
                    FileOutputStream file = new FileOutputStream("student.txt",true);//파일 열기
                    OutputStreamWriter output = new OutputStreamWriter(file,"utf-8");
                    BufferedWriter writer = new BufferedWriter(output);
                    Student stu = new Student(pNum.getText(), name.getText(), depart_list.getSelectedItem().toString());
                    str = String.format("%s/%s/%s/%s/%s%n",stu.getId(),stu.getName(),stu.getPassWord(),stu.getPeopleNum(),stu.getDepartMent());
                    writer.write(str); //파일에 객체 정보를 저장
                    writer.close();
                    showMessageDialog(null,stu.getId() +" " + stu.getName() + "학생이 등록 되었습니다.");
                }catch(IOException e){
                    e.printStackTrace();
                }
            }else if(pro_butt.isSelected()){ //교수 파일에 입력
                try{
                    FileOutputStream file = new FileOutputStream("professer.txt",true);//파일 열기
                    OutputStreamWriter output = new OutputStreamWriter(file,"utf-8");
                    BufferedWriter writer = new BufferedWriter(output);
                    Professer pro = new Professer(pNum.getText(), name.getText(), depart_list.getSelectedItem().toString());
                    str = String.format("%s/%s/%s/%s%s%n",pro.getId(),pro.getName(),pro.getPassWord(),pro.getPeopleNum(), pro.getDepartMent());
                    writer.write(str); //파일에 객체 정보를 저장
                    writer.close();
                    showMessageDialog(null,pro.getId() +" " + pro.getName() + "교수가 등록 되었습니다.");

                }catch(IOException e){
                    e.printStackTrace();
                }
            }
            else{
                showMessageDialog(null,"직군을 선택하지 않았습니다.");
            }
        }
    }//GEN-LAST:event_insert_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(School_insert_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(School_insert_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(School_insert_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(School_insert_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new School_insert_user().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> depart_list;
    private javax.swing.JButton insert_Exit;
    private javax.swing.JTabbedPane insert_Info;
    private javax.swing.JButton insert_Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JRadioButton lec_butt;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pNum;
    private javax.swing.JRadioButton pro_butt;
    private javax.swing.JRadioButton sch_butt;
    private javax.swing.JRadioButton stu_butt;
    // End of variables declaration//GEN-END:variables
}
